server:
  address: 0.0.0.0
  port: 8082
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
  datasource:
    # Thêm các tham số để driver kết nối mượt hơn
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sapassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Ép Hibernate sử dụng đúng Dialect cho MySQL
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Cấu hình bổ sung để tránh lỗi metadata
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true