server:
  port: 8085
  address: 0.0.0.0

spring:
  application:
    name: ai-service
  ai:
    openai:
      api-key: AIzaSyAsoGTo5LB4AX8cS4e8BIGJ88dh9x_8B3I
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gpt-3.5-turbo # Dùng gpt-3.5-turbo làm alias để tương thích với Gemini OpenAI endpoint
          temperature: 0.7
    retry:
      max-attempts: 1 # Tắt Retry để chuyển sang Fallback ngay lập tức
